In [4]:
# !pip install tensorflow

In [13]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [5]:
tf.__version__

'2.8.0'

# Define Model

In [6]:
model = tf.keras.Sequential()

## Add Layers
* Input
* Middle- Dense
* Output

In [7]:
model.add(tf.keras.layers.Input(shape=(5,)))

In [8]:
model.add(tf.keras.layers.Dense(4,activation=tf.keras.activations.sigmoid,name="hidden_layer_1"))

In [9]:
model.add(tf.keras.layers.Dense(5,activation=tf.keras.activations.sigmoid,name="hidden_layer_2"))

In [10]:
model.add(tf.keras.layers.Dense(1,activation=tf.keras.activations.sigmoid,name="output_layer"))

## Compile
* Loss function : tells the difference between my tarhet and the output
* optimizer : algorithm which makes the model as accurate as possible; minimizing the loss function by adjusting weights
* metrics : it is model performance parmeter ; judges on validation set after each epoch and has nothing to do with the optimizer

In [11]:
model.compile(loss=tf.keras.losses.binary_crossentropy,optimizer=tf.keras.optimizers.SGD(),
              metrics=[tf.keras.metrics.Accuracy()])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden_layer_1 (Dense)      (None, 4)                 24        
                                                                 
 hidden_layer_2 (Dense)      (None, 5)                 25        
                                                                 
 output_layer (Dense)        (None, 1)                 6         
                                                                 
Total params: 55
Trainable params: 55
Non-trainable params: 0
_________________________________________________________________


In [14]:
data = np.random.randint(0,10,size=(1000,5))  
pd.DataFrame(data).head()

0  1  2  3  4
0  1  8  6  3  1
1  7  6  8  2  0
2  5  5  7  8  5
3  6  4  5  0  0
4  2  7  7  1  9

In [15]:
y = np.random.randint(0,2,size=(1000))
y[:10]  

array([0, 0, 1, 0, 1, 1, 1, 1, 1, 1])

## Fit

In [16]:
model.fit(x=data,y=y,epochs=100)

Epoch 1/100
32/32 [==============================] - 1s 3ms/step - loss: 0.6950 - accuracy: 0.0000e+00
Epoch 2/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6948 - accuracy: 0.0000e+00
Epoch 3/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6945 - accuracy: 0.0000e+00
Epoch 4/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6943 - accuracy: 0.0000e+00
Epoch 5/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6943 - accuracy: 0.0000e+00
Epoch 6/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6943 - accuracy: 0.0000e+00
Epoch 7/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6942 - accuracy: 0.0000e+00
Epoch 8/100
32/32 [==============================] - 0s 3ms/step - loss: 0.6942 - accuracy: 0.0000e+00
Epoch 9/100
32/32 [==============================] - 0s 4ms/step - loss: 0.6941 - accuracy: 0.0000e+00
Epoch 10/100
32/32 [==============================] - 0s 3ms/step - loss:

In [17]:
model.predict(x=data)>=0.5

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

# Extra

In [18]:
vector_tf = tf.constant([0,1,2,3,4])

vector_np  = np.array([0,1,2,3,4])

matrix_tf = tf.constant([[0,1],[2,3],[3,4]])

matrix_np = np.array([[0,1],[2,3],[3,4]])

t3_tf = tf.constant([[[0,1],[2,3],[3,4]]]*5)

print(t3_tf.shape)

t3_np = np.array([[[0,1],[2,3],[3,4]]]*5)

In [25]:
t3_tf

<tf.Tensor: shape=(5, 3, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3],
        [3, 4]],

       [[0, 1],
        [2, 3],
        [3, 4]],

       [[0, 1],
        [2, 3],
        [3, 4]],

       [[0, 1],
        [2, 3],
        [3, 4]],

       [[0, 1],
        [2, 3],
        [3, 4]]])>

In [26]:
arr = np.random.randn(2,2,2,2)

In [27]:
arr.shape

(2, 2, 2, 2)

In [28]:
#Change Std deviation to 1
arr = arr * 1

In [29]:
#Change Mean to 1
arr = arr + 1

In [30]:
tf_arr = tf.constant(arr)

In [31]:
tf_arr.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2, 2, 2), dtype=float64, numpy=
array([[[[-0.52128042, -0.56628827],
         [ 1.658294  ,  1.80212229]],

        [[ 1.05024016,  0.60852315],
         [ 1.71919035,  0.60925883]]],


       [[[-0.90240733, -0.38656609],
         [ 0.084713  ,  1.03648725]],

        [[-0.01743295,  1.44542714],
         [-0.9150744 ,  0.51290674]]]])>>

In [32]:
arr2 = tf.random.normal((2,2,2),mean=1,stddev=1,name='My_Tensor')
arr2.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[ 0.78822094,  0.19648248],
        [ 0.8073236 , -0.15280497]],

       [[ 0.1269843 ,  0.63032305],
        [ 1.6695364 ,  2.4225016 ]]], dtype=float32)>>

In [33]:
#Mathematical Operations
arr_x = tf.Variable([range(5)]*5)

In [34]:
arr_x

<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])>

In [35]:
arr_y = tf.Variable([range(5,10)]*5)

In [36]:
arr_y

<tf.Variable 'Variable:0' shape=(5, 5) dtype=int32, numpy=
array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])>

In [37]:
sample = tf.random.uniform((2,2),dtype=tf.int32,maxval=100)
sample

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1, 84],
       [25, 56]])>

In [38]:
sample_prod = tf.multiply(sample,sample)
sample_prod

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   1, 7056],
       [ 625, 3136]])>

In [39]:
sample_prod2 = sample * sample
sample_prod2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   1, 7056],
       [ 625, 3136]])>

In [40]:
tf.pow(sample, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   1, 7056],
       [ 625, 3136]])>

In [41]:
w_matrix = tf.Variable([[0.5],[1],[-1.2]])

In [42]:
w_matrix

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.5],
       [ 1. ],
       [-1.2]], dtype=float32)>

In [43]:
x_matrix = tf.Variable([[0.2, 1, 0.5]])
x_matrix

<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[0.2, 1. , 0.5]], dtype=float32)>

In [44]:
wx = tf.matmul(x_matrix,w_matrix)

In [45]:
b_matrix = tf.Variable([0.01])

In [46]:
z_matrix = tf.add(w_matrix,b_matrix)
z_matrix

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 0.51],
       [ 1.01],
       [-1.19]], dtype=float32)>

In [47]:
output = tf.sigmoid(z_matrix,)

In [48]:
print(output.numpy()[0][0])

0.62480646
